W7D3/bluebird-feb-2020-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # post '/users', to: 'users#create'
  # patch '/users/:id', to: 'users#update'
  # delete '/users/:id', to: 'users#destroy'

  resources :users do
    resources :chirps, only: [:index] # get '/users/:user_id/chirps, to: 'chirps#index'
  end

  resources :chirps, only: [:show, :create] # get '/chirps/:id', to: 'chirps#show'

  resource :session, only: [:new, :create, :destroy] # only one session
  
end

W7D3/bluebird-feb-2020-master/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :bigint           not null, primary key
#  username              :string           not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  email                 :string           not null
#  age                   :integer          not null
#  political_affiliation :string
#

class User < ApplicationRecord
  # attributes that are columns automatically get getters/setters
  
  # Validations are run when you save (.save)
  validates :username, :email, :session_token, presence: true, uniqueness: true 
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true } # plain text password must be atleast 6 characters
  # validate :custom_validation_method
  
  # Validations call getter methods of things that are being validated
  # need getter for password in order for the validation to work
  attr_reader :password 

  # calls ensure_session_token right before validations are run (before saving to db)
  before_validation :ensure_session_token
  # after_initialize :ensure_session_token

  has_many :chirps,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Chirp

  has_many :likes,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Like

  has_many :liked_chirps,
    through: :likes,
    source: :chirp 

  has_many :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment

  def self.find_by_credentials(username, password)
    # Check that the user exists in db
    user = User.find_by(username: username)

    # don't need to check password if there is no user in db
    return nil unless user

    # assume user is in db
    # verify that the supplied password matches what we have on file for user
    user.is_password?(password) ? user : nil # our #is_password? method
  end
  
  def is_password?(password)
    # take stringified pw_digest and turn in an PW object
    # password_object = BCrypt::Password.new(self.password_digest) 
    # use BCrypt's is_password? to check equality
    # password_object.is_password?(password)

    # one liner version
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    # need to create instance variable for getter method/validations
    @password = password # plain text

    # Turn plain text password into digest and set as user's password_digest
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    # generates session token for user if it's not already set
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    # change session token
    self.session_token = SecureRandom.urlsafe_base64

    # save to the db, loudly
    self.save!

    # return session_token
    self.session_token
  end
end

W7D3/bluebird-feb-2020-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_is_user, only: [:edit, :update]

  def index
    @users = User.all

    # render json: users
    render :index
  end

  def show
    # Need to use instance variables for views!!
    @user = User.find(params[:id])
    
    # render json: user
    render :show
  end

  def new
    @user = User.new # empty/blank user
    render :new
  end
  
  def create
    @user = User.new(user_params)
    # sets attributes for columns, no password column

    if @user.save
      # login the user
      login!(@user) #method comes from application controller
      
      # redirect_to "/users/#{user.id}"
      redirect_to user_url(@user)
    else
      # render json: user.errors.full_messages, status: 422
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      # redirect_to "/users/#{user.id}"
      redirect_to user_url(@user)
    else
      render json: @user.errors.full_messages, status: 422
    end
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy

    # render json: @user
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :age, :political_affiliation, :password)
  end

  def require_is_user
    redirect_to users_url unless current_user.id == params[:id].to_i
  end

  # params hash
  # {
  #   user: {
  #     username: 'asdf',
  #     age: 12
  #   }
  # }
  
end

W7D3/bluebird-feb-2020-master/app/helpers/users_helper.rb
module UsersHelper
end

W7D3/bluebird-feb-2020-master/app/views/users/_form.html.erb
<% if type == :new %>
  <% banana = users_url %>
  <% button_txt = "Create User" %>
<% else %>
  <% banana = user_url(user) %>
  <% button_txt = "Update User" %>
<% end%>

<form action="<%= banana %>" method="POST">
  <%= auth_token %>
  <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label>
    Username
    <input id="username" type="text" name="user[username]" value="<%= user.username %>">
  </label>

  <% if type != :edit %>
    <label>
      Password
      <input id="password" type="password" name="user[password]" value="">
    </label>
  <% end %>

  <label>
    Age
    <input id="age" type="text" name="user[age]" value="<%= user.age %>">
  </label>

  <label>
    Email
    <input id="email" type="text" name="user[email]" value="<%= user.email %>">
  </label>

  <button type="submit"><%= button_txt %></button>
</form>

W7D3/bluebird-feb-2020-master/app/views/users/_user.html.erb
<% if action == :show %>
  <li><a href="<%= users_url %>">Back to Index</a></li> 
<% else %>
  <li><a href="<%= user_url(user) %>">User Show Page</a></li>
<% end %>

<ul>
  <li><%= user.username %></li>
  <li><%= user.age %></li>
  <li><%= user.email %></li>
</ul>
<a href="<%= user_chirps_url(user) %>">My Chirps</a>
<li>
  <form action="<%= user_url(user) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <button type="submit">BE GONE</button>
  </form>
</li>

W7D3/bluebird-feb-2020-master/app/views/users/edit.html.erb
<h1>Update User Information</h1>
<%= render 'form', type: :edit, user: @user %>

W7D3/bluebird-feb-2020-master/app/views/users/index.html.erb
<h1>List of all Users</h1>
<a href="<%= new_user_url %>">Sign Up</a>
<ul>
  <% @users.each do |user| %>
    <% if current_user && current_user.id == user.id %>
      <a href="<%= edit_user_url(user) %>">Edit</a>
    <% end %>
    <%# render <partial_name>, <partial_variable>: <value> %>
    <%= render 'user', user: user, action: :index %>
  <% end %>
</ul>

W7D3/bluebird-feb-2020-master/app/views/users/new.html.erb
<h1>Create New User</h1>
<%= render 'form', type: :new, user: @user %>

W7D3/bluebird-feb-2020-master/app/views/users/show.html.erb
<h1>User Show Page</h1>
<a href="<%= edit_user_url %>">Edit</a>
<%= render 'user', { user: @user, action: :show } %>