W7D3/bluebird-feb-2020-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # post '/users', to: 'users#create'
  # patch '/users/:id', to: 'users#update'
  # delete '/users/:id', to: 'users#destroy'

  resources :users do
    resources :chirps, only: [:index] # get '/users/:user_id/chirps, to: 'chirps#index'
  end

  resources :chirps, only: [:show, :create] # get '/chirps/:id', to: 'chirps#show'

  resource :session, only: [:new, :create, :destroy] # only one session
  
end

W7D3/bluebird-feb-2020-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bluebird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# templates we write go here %>
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <% if logged_in? %>
      <marquee scrollamount="30">Hi, <%= current_user.username %></marquee>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE"> 
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
        <button type="submit">Logout!</button>
      </form>

      <form action="<%= chirps_url %>" method="post">
        <%= auth_token %>
        <input type="submit">
      </form>
    <% end %>
    <%= yield %> 
  </body>
</html>