W7D3/goal_setter/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

W7D3/goal_setter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D3/goal_setter/app/models/user.rb
class User < ApplicationRecord
    validates :username, :email, :session_token, presence:true, uniqueness:true
    validates :password_digest, presence:true
    validates :password, length: {minimum: 6, allow_nil: true} 

    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil unless user
        user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end
    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end
    

        
    


end

W7D3/goal_setter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def login!(user)
        session[:session_token] = user.reset_session_token!
    end
end

W7D3/goal_setter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

W7D3/goal_setter/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :age, :password)
        
    end
end

W7D3/goal_setter/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D3/goal_setter/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D3/goal_setter/app/helpers/users_helper.rb
module UsersHelper
end

W7D3/goal_setter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalSetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

W7D3/goal_setter/app/views/users/_form.html.erb
<% if type == :new %>
    <% url = users_url %>
    <% button_text = "Create User" %>
<% else %>
    <%url = user_url(user)  %>
    <% button_text = 'Update User' %>
<% end %>

<form action= '<%=url%>' method= 'POST'> 
<%# <%= auth_token %> %>
<% if type == :edit %>
<input type="hidden" name= "_method" value= "PATCH">
<% end %>


<label>
Username
<input id="username" type="text" name= "user[username]" value= "<%=user.username %>%"> 
</label>

<label>
Age
<input id="age" type="text" name= "user[age]" value= "<%=user.age %>%"> 
</label>

<label>
Email
<input id="email" type="text" name= "user[email]" value= "<%=user.email %>%"> 
</label>

<% if type != :edit %>
<label>
Password
<input id="password" type="text" name= "user[password]" value= "<%=user.password %>%"> 
</label>
<% end %>
<button type= "submit"><%= button_text %></button>
</form>

W7D3/goal_setter/app/views/users/new.html.erb
<h1>Create New User</h1>
<%= render 'form', type: :new, user: @user %>

W7D3/goal_setter/app/views/users/show.html.erb
<h1>User Show Page</h1>
<a href="<%= edit_user_url %>">Edit</a>
<%= render 'user', { user: @user, action: :show } %>